language: objective-c
osx_image: xcode10
cache: cocoapods

env:
  global:
  - LANG=en_US.UTF-8

  - WORKSPACE="OTAcceleratorCore.xcworkspace"
  - IOS_SCHEME="OTAcceleratorCore"
  - IOS_SDK=iphonesimulator12.0

  matrix:

  - DESTINATION="OS=10.3.1,name=iPhone 6s"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES" RUN_UI_TESTS="YES"
  - DESTINATION="OS=12.0,name=iPhone X"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES" RUN_UI_TESTS="YES"
before_install:
  - gem install cocoapods --pre
  - pod update

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
    pod lib lint --use-libraries --allow-warnings --verbose;
  fi

- if [ $RUN_TESTS == "YES" ]; then
    travis_retry xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
    travis_retry xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi
notifications:
  slack:
    rooms:
      secure: ByutywWNWBQURMBuwkWwlOM2VuoAqBLQRm80LgXLl7+tpmCqhQtMdJ1msMpW0DqU/uwEymNEd/vi45+LBT9mBU5mmU/g0Dwgt6blIOAiFBEghO4tyb+EQDYrOhJLeacalcCdB/LaynTFn8KXGYOHK3nxlDORXfFEAv1vbvxVu8pJaEh9zXmyEDhIJ33A4zai5i/QI/EwSJq+9X1U2k6ss4H33ivigfZThZ99ors3X0aHJH2hL3ObLKtGqKZkGLagtZDAPWCiVeK+oKOMAjFMX4Cu+C3+5y4kLarca1bAddtU5ZwFJfWo2AUWw75NPgiwpjPdj0ORRm3zU1+eKBCzTMkJoA1D4EC9SMWWIquPP9Kv5jAR92nMFsRSA6J+/n7G982tDafFRJTwwreLNn2NHG8wqgPWNCCHjH+J7HBDfYuhPRMmaFNAkAsHcIzJVNnYPdkm0cGIpf0EFWApmY8qVp+RX1OfXcqQkC7ZlzjPfvoUzYEgmj//YMLAzX+A4Dz/NRMtHzeauPFH1gxsQ2PFPRKWPvRkSQQIhyKNBT1NfKfmvlchm2cGEj+zCWbo2wfQxx4kx/PHIHhLYNjJyUR9tUJcEdfuDEPh4/3y9oP+KkUVi7BF1gZA+YSuY2C8uiQnanFGkUFdUaSjx2ZN21F+0L1Irw2l+ogeL8qq6bH/FE8=
